import Link from "next/link";
import { WebsiteRoastForm } from "@/components/public/WebsiteRoastForm";

export const metadata = {
  title: "Free Website Roast | MixedMakerShop",
  description:
    "Get a free website roast and find out what may be hurting your trust, leads, and conversions.",
};

export default function WebsiteRoastPage() {
  return (
    <>
      <section className="hero roast-hero">
        <div className="container">
          <h1 className="h1">Get Your Website Roasted for Free</h1>
          <p className="subhead">
            I&apos;ll review your website and point out what may be hurting your trust, conversions, clarity, and first
            impression.
          </p>
          <p className="hero-microproof" style={{ margin: "10px 0 0" }}>
            Perfect for small businesses, contractors, local services, startups, and personal brands.
          </p>
          <div className="btn-row" style={{ marginTop: 20 }}>
            <a className="btn gold" href="#roast-form">
              Get My Free Website Roast
            </a>
            <a className="btn ghost" href="#what-i-review">
              See What I Review
            </a>
          </div>
          <div className="trust-line" style={{ marginTop: 18 }}>
            <span>Free review</span>
            <span>No obligation</span>
            <span>Actionable feedback</span>
          </div>
          <p className="small" style={{ margin: "10px 0 0", opacity: 0.85 }}>
            Reviewed personally — not generated by a generic auto-audit tool.
          </p>
        </div>
      </section>

      <section className="section" id="what-is-roast">
        <div className="container">
          <h2 className="section-heading">What Is a Website Roast?</h2>
          <p className="subhead" style={{ margin: "0 0 28px", maxWidth: "65ch" }}>
            A website roast is a practical review of your site from the perspective of trust, clarity, user experience,
            and lead generation. I&apos;ll point out what&apos;s working, what feels weak, and where your site may be losing
            attention, confidence, or conversions.
          </p>
          <div className="how-it-works-grid roast-cards">
            <div className="how-it-works-card">
              <h3 className="how-it-works-title">First Impression</h3>
              <p className="how-it-works-copy">Does your site immediately look trustworthy and relevant?</p>
            </div>
            <div className="how-it-works-card">
              <h3 className="how-it-works-title">Clarity</h3>
              <p className="how-it-works-copy">
                Is it obvious what you do, who you help, and what visitors should do next?
              </p>
            </div>
            <div className="how-it-works-card">
              <h3 className="how-it-works-title">Conversion</h3>
              <p className="how-it-works-copy">
                Are your calls to action, layout, and messaging helping visitors take action?
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="section roast-review-section" id="what-i-review">
        <div className="container">
          <h2 className="section-heading">What I Review</h2>
          <div className="roast-checklist" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 14 }}>
            <div className="roast-checklist-item card">
              <span className="roast-checklist-label">Headline clarity</span>
              <p className="small" style={{ margin: "4px 0 0" }}>
                Does your main headline quickly communicate your offer or value?
              </p>
            </div>
            <div className="roast-checklist-item card">
              <span className="roast-checklist-label">Visual trust</span>
              <p className="small" style={{ margin: "4px 0 0" }}>
                Does the design feel credible and aligned with your brand?
              </p>
            </div>
            <div className="roast-checklist-item card">
              <span className="roast-checklist-label">Calls to action</span>
              <p className="small" style={{ margin: "4px 0 0" }}>
                Are your buttons and links clear, visible, and compelling?
              </p>
            </div>
            <div className="roast-checklist-item card">
              <span className="roast-checklist-label">Mobile friendliness</span>
              <p className="small" style={{ margin: "4px 0 0" }}>Does your site work well and look good on phones?</p>
            </div>
          </div>
        </div>
      </section>

      <section className="section" id="roast-form">
        <div className="container">
          <div className="panel">
            <h2 style={{ margin: "0 0 14px" }}>Get Your Free Website Roast</h2>
            <p className="subhead" style={{ margin: "0 0 24px" }}>
              Enter your website and email. I&apos;ll review it personally and send feedback within 24–48 hours.
            </p>
            <WebsiteRoastForm />
          </div>
        </div>
      </section>
    </>
  );
}
