export type ScoutSummary = {
  last_run_time: string | null;
  leads_found_today: number;
  top_opportunities_count: number;
  followups_due: number;
  today_businesses_discovered: number;
  today_analyzed_total: number;
  today_high_opportunity_total: number;
  dashboard_businesses_discovered: number;
  dashboard_websites_audited: number;
  dashboard_high_opportunities: number;
  dashboard_outreach_sent: number;
};

export type ScoutLead = {
  id?: string | null;
  business_name?: string | null;
  category?: string | null;
  city?: string | null;
  address?: string | null;
  website?: string | null;
  distance?: number | null;
  score?: number | null;
  opportunity_score?: number | null;
  lead_bucket?: string | null;
  lead_type?: string | null;
  lane?: string | null;
  best_contact_method?: string | null;
  best_pitch_angle?: string | null;
  recommended_next_action?: string | null;
  opportunity_reason?: string | null;
  close_probability?: string | null;
  opportunity_signals?: string[];
  slug?: string | null;
};

export type TopOpportunitiesResponse = {
  leads: ScoutLead[];
  plan_notice?: string;
  plan?: string;
};

export type RunScoutResponse = {
  ok?: boolean;
  success?: boolean;
  job_id?: string;
  status?: string;
  progress?: number;
  poll_url?: string;
  error?: string;
  message?: string;
  user_message?: string;
};

export type ScoutScanScope = "single_city" | "nearby_cities" | "arkansas_region" | "all_arkansas";
export type ScoutScanDepth = "quick" | "normal" | "deep";
export type ScoutDiscoveryMode = "reduced_free" | "paid_discovery";

export type ScoutScanSettings = {
  scope: ScoutScanScope;
  single_city?: string | null;
  region?: string | null;
  categories: string[];
  issue_filters: string[];
  depth: ScoutScanDepth;
  discovery_mode?: ScoutDiscoveryMode;
  mode?: "reduced" | "discovery";
  city?: string | null;
  category?: string | null;
  lead_limit?: number | null;
};

export type ScoutJobStatusResponse = {
  id: string;
  status: "queued" | "running" | "finished" | "failed" | string;
  progress: number;
  message?: string | null;
  stage?: string | null;
  summary: string | null;
  error: string | null;
  created_at?: string | null;
  started_at?: string | null;
  finished_at?: string | null;
  scan_settings?: ScoutScanSettings | null;
  persistence_debug?: {
    scout_run_saved?: boolean;
    opportunities_created?: number;
    opportunities_updated?: number;
    case_files_created?: number;
    case_files_updated?: number;
    leads_created?: number;
    duplicates_skipped?: number;
    workspace_id?: string | null;
    backend_supabase_url?: string | null;
    admin_supabase_url?: string | null;
    intake?: {
      workspace_id?: string | null;
      opportunities_found?: number;
      opportunities_loaded?: number;
      total_records?: number;
      scanned_count?: number;
      enriched_count?: number;
      opportunities_evaluated?: number;
      evaluated?: number;
      eligible_for_lead_creation?: number;
      eligible?: number;
      leads_created?: number;
      created?: number;
      duplicates_skipped?: number;
      duplicate_skipped?: number;
      insert_failed?: number;
      filtered_out?: number;
      filtered_low_score?: number;
      filtered_missing_contact_path?: number;
      filtered_missing_email?: number;
      filtered_missing_opportunity_reason?: number;
      filtered_closed_or_dnc?: number;
      filtered_missing_business_name?: number;
      filtered_missing_workspace?: number;
      filtered_existing_linked_opportunity?: number;
      duplicate_by_website?: number;
      duplicate_by_phone?: number;
      duplicate_by_business_name_city?: number;
      leads_with_email?: number;
      leads_with_phone?: number;
      leads_with_contact_page?: number;
      leads_with_facebook?: number;
      leads_with_no_contact_path?: number;
      websites_found?: number;
      contact_pages_found?: number;
      facebook_found?: number;
      phone_found?: number;
      no_contact_path?: number;
      phones_found?: number;
      facebook_links_found?: number;
      records_with_no_contact?: number;
      businesses_found?: number;
      no_website_found?: number;
      facebook_only?: number;
      phone_only?: number;
      leads_created_with_website?: number;
      leads_created_without_website?: number;
      actionable_email_leads_created?: number;
      research_later_leads_created?: number;
      door_to_door_candidates_created?: number;
      archived_low_priority_created?: number;
      google_discovery_used?: boolean;
      reduced_mode?: boolean;
      stored_records_scanned?: number;
      records_enriched?: number;
      emails_found?: number;
      actionable_email_leads?: number;
      contact_available?: number;
      research_later?: number;
      door_to_door_candidates?: number;
      skipped?: number;
      leads_skipped_due_no_email?: number;
      leads_created_with_low_score?: number;
      leads_created_high_score?: number;
      reason_counts?: {
        missing_business_name?: number;
        missing_workspace_id?: number;
        missing_contact_path?: number;
        missing_email?: number;
        missing_opportunity_reason?: number;
        score_below_threshold?: number;
        duplicate_by_linked_opportunity_id?: number;
        duplicate_by_website?: number;
        duplicate_by_phone?: number;
        duplicate_by_business_name_city?: number;
        insert_error?: number;
      };
      query_error?: string | null;
      intake_threshold_used?: number;
    } | null;
    reduced_mode_notice?: string | null;
    places_reduced_mode?: boolean;
    errors?: Array<Record<string, unknown>>;
  } | null;
};

export type ScoutIntegrationResult<T> = {
  configured: boolean;
  data: T | null;
  error: string | null;
};
