// 3D Pop-Out Scenes catalog. Each scene is a looping pop-out video that doubles
// as a ready-to-post Facebook/Instagram ad (rendered as a social-post card on
// /3d-scenes). Add new scenes here as they're produced — the gallery scales
// automatically. Target library size: 50.

export interface ThreeDScene {
  id: string;
  /** Gallery heading / internal name. */
  title: string;
  /** Who it's for. */
  niche: string;
  video: string;
  poster: string;
  /** The mock post author shown on the card. */
  author: string;
  handle: string;
  location?: string;
  /** Ready-to-paste Facebook / Instagram caption. */
  caption: string;
  likes: number;
  comments: number;
  shares: number;
}

export const THREE_D_SCENES: ThreeDScene[] = [
  {
    id: "money",
    title: "Money Rain",
    niche: "Small business · financing",
    video: "/videos/scenes/money.mp4",
    poster: "/videos/scenes/money-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "💸 A website that pays for itself? That's the MixedMakerShop way. We build sites that actually bring in customers — and we can even help you Get a Loan to fund the build. One umbrella, every service. 🌂",
    likes: 1243,
    comments: 86,
    shares: 41,
  },
  {
    id: "coffee",
    title: "Coffee Pour",
    niche: "Coffee shops & cafés",
    video: "/videos/scenes/coffee.mp4",
    poster: "/videos/scenes/coffee-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "☕ Pour-over perfection — and a coffee-shop website to match. We design café sites that get found on Google and fill seats. Free coffee-shop mockup, on us. #CoffeeShop #HotSpringsAR",
    likes: 892,
    comments: 54,
    shares: 28,
  },
  {
    id: "fire",
    title: "Fire & Embers",
    niche: "Bold brands · hot deals",
    video: "/videos/scenes/fire.mp4",
    poster: "/videos/scenes/fire-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🔥 Your competition wishes their website looked this hot. Sites, SEO, and AI tools that bring in real customers. Hot deals all month long. 🌂 #SmallBusiness #HotSpringsAR",
    likes: 1561,
    comments: 103,
    shares: 67,
  },
  {
    id: "wash",
    title: "Pressure-Wash Sweep",
    niche: "Pressure washing & cleaning",
    video: "/videos/scenes/wash.mp4",
    poster: "/videos/scenes/wash-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "💦 Watch the grime disappear. Run a pressure-washing business in Hot Springs? We'll build you a site that books jobs while you work. Free estimate-ready mockup. #PressureWashing",
    likes: 734,
    comments: 39,
    shares: 22,
  },
  {
    id: "confetti",
    title: "Father's Day Confetti",
    niche: "Holidays & promotions",
    video: "/videos/scenes/confetti.mp4",
    poster: "/videos/scenes/confetti-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🎉 Happy Father's Day from MixedMakerShop! Treat the maker, builder, or business owner in your life — websites, 3D printing, and local tech help, all under one umbrella. 🌂 #FathersDay",
    likes: 2104,
    comments: 147,
    shares: 95,
  },
  {
    id: "grass",
    title: "Fresh-Cut Sweep",
    niche: "Lawn care & property care",
    video: "/videos/scenes/grass.mp4",
    poster: "/videos/scenes/grass-poster.jpg",
    author: "Fresh Cut Property Care",
    handle: "@freshcutpropertycare",
    location: "Hot Springs & Lonsdale, AR",
    caption:
      "🌿 Fresh cut, fresh site. Fresh Cut Property Care keeps Hot Springs yards sharp — and a website that ranks keeps their phone ringing. Lawn care, cleanup & more. Free estimate. #LawnCare",
    likes: 658,
    comments: 31,
    shares: 19,
  },
  {
    id: "snow",
    title: "Snowfall",
    niche: "Any season · stand out",
    video: "/videos/scenes/snow.mp4",
    poster: "/videos/scenes/snow-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "❄️ Make your business impossible to scroll past — any season. We build websites that get found on Google and bring in real customers. One umbrella, every service. 🌂 #HotSpringsAR",
    likes: 1012,
    comments: 58,
    shares: 33,
  },
  {
    id: "storm",
    title: "Lightning Strike",
    niche: "Speed · performance",
    video: "/videos/scenes/storm.mp4",
    poster: "/videos/scenes/storm-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "⚡ Electrify your online presence. Slow, invisible website? We build fast sites that actually rank and convert. Power up your small business. 🌂 #HotSpringsAR #WebDesign",
    likes: 1187,
    comments: 71,
    shares: 44,
  },
  {
    id: "bubbles",
    title: "Soap & Shine",
    niche: "Cleaning & detailing",
    video: "/videos/scenes/bubbles.mp4",
    poster: "/videos/scenes/bubbles-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🫧 Squeaky clean — site and all. Cleaning or pressure-washing pro? We'll build you a site that books jobs while you scrub. Free mockup. #CleaningBusiness #HotSpringsAR",
    likes: 803,
    comments: 42,
    shares: 25,
  },
  {
    id: "leaves",
    title: "Autumn Leaves",
    niche: "Lawn care & seasonal",
    video: "/videos/scenes/leaves.mp4",
    poster: "/videos/scenes/leaves-poster.jpg",
    author: "Fresh Cut Property Care",
    handle: "@freshcutpropertycare",
    location: "Hot Springs & Lonsdale, AR",
    caption:
      "🍂 Season's changing — is your yard ready? Fresh Cut Property Care handles cleanup, hauling and more, and a site that ranks keeps the calls coming. Free estimate. #PropertyCare #HotSpringsAR",
    likes: 712,
    comments: 36,
    shares: 21,
  },
  {
    id: "sparkle",
    title: "Golden Sparkle",
    niche: "Premium brands · cafés",
    video: "/videos/scenes/sparkle.mp4",
    poster: "/videos/scenes/sparkle-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "✨ Make your café shine online. Premium coffee deserves a premium website — found on Google, built to fill seats. Free coffee-shop mockup. ☕ #CoffeeShop #HotSpringsAR",
    likes: 948,
    comments: 61,
    shares: 37,
  },
  {
    id: "rain",
    title: "Rain on Glass",
    niche: "Small business · lead-gen",
    video: "/videos/scenes/rain.mp4",
    poster: "/videos/scenes/rain-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🌧️ When it rains, it pours — leads, that is. A website built to bring in customers, rain or shine. Websites, SEO and AI help under one umbrella. 🌂 #HotSpringsAR",
    likes: 1095,
    comments: 64,
    shares: 39,
  },
  {
    id: "steam",
    title: "Steam & Sizzle",
    niche: "Restaurants & cafés",
    video: "/videos/scenes/steam.mp4",
    poster: "/videos/scenes/steam-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🍽️ Fresh, hot, and ready to order. Run a restaurant in Hot Springs? We build menus and sites that get found on Google and fill tables. Free mockup. #Restaurant #HotSpringsAR",
    likes: 1340,
    comments: 88,
    shares: 52,
  },
  {
    id: "print",
    title: "3D Print Glow",
    niche: "3D printing · makers",
    video: "/videos/scenes/print.mp4",
    poster: "/videos/scenes/print-poster.jpg",
    author: "GiGi's Print Shop",
    handle: "@gigisprintshop",
    location: "Hot Springs, Arkansas",
    caption:
      "🖨️ From idea to object. Need a custom part, mount, or fix? GiGi's Print Shop prints PLA on demand — and a site that ranks keeps the orders coming. #3DPrinting #HotSpringsAR",
    likes: 876,
    comments: 47,
    shares: 29,
  },
  {
    id: "petals",
    title: "Petal Drift",
    niche: "Churches & community",
    video: "/videos/scenes/petals.mp4",
    poster: "/videos/scenes/petals-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🕊️ A warm welcome — online, too. We build clean, caring church websites that help visitors plan their first visit. Free mockup for your congregation. #ChurchWebsite #HotSpringsAR",
    likes: 624,
    comments: 33,
    shares: 24,
  },
  {
    id: "smoke",
    title: "Fog Reveal",
    niche: "Brand reveal · mystery",
    video: "/videos/scenes/smoke.mp4",
    poster: "/videos/scenes/smoke-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "💨 Out of the fog, into the spotlight. Make your business the one people actually find. Websites, SEO and AI tools under one umbrella. 🌂 #HotSpringsAR",
    likes: 901,
    comments: 49,
    shares: 31,
  },
  {
    id: "rays",
    title: "Light Rays",
    niche: "Small business · hero",
    video: "/videos/scenes/rays.mp4",
    poster: "/videos/scenes/rays-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🌅 Let your business shine. A website built to get found on Google and bring in real customers, day in and day out. 🌂 #SmallBusiness #HotSpringsAR",
    likes: 1058,
    comments: 60,
    shares: 35,
  },
  {
    id: "neon",
    title: "Neon Shine",
    niche: "Premium brands · cafés",
    video: "/videos/scenes/neon.mp4",
    poster: "/videos/scenes/neon-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🌟 Glow up your café's online presence. Premium coffee, premium website — found on Google, built to fill seats. Free mockup. ☕ #CoffeeShop #HotSpringsAR",
    likes: 933,
    comments: 57,
    shares: 34,
  },
  {
    id: "eagle",
    title: "Eagle Breakout",
    niche: "Bold brands · hero",
    video: "/videos/scenes/eagle.mp4",
    poster: "/videos/scenes/eagle-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🦅 Soar above the competition. We build bold websites that get your business seen and bring in customers. One umbrella, every service. 🌂 #HotSpringsAR #SmallBusiness",
    likes: 1712,
    comments: 109,
    shares: 74,
  },
  {
    id: "puppy",
    title: "Puppy Pop-Out",
    niche: "Scroll-stoppers · any brand",
    video: "/videos/scenes/puppy.mp4",
    poster: "/videos/scenes/puppy-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🐶 Aww — caught your eye, didn't it? That's exactly what a pop-out video ad does for YOUR business. We build sites + scroll-stopping content. 🌂 #HotSpringsAR",
    likes: 2456,
    comments: 168,
    shares: 121,
  },
  {
    id: "cat",
    title: "Cat Paw-Through",
    niche: "Scroll-stoppers · any brand",
    video: "/videos/scenes/cat.mp4",
    poster: "/videos/scenes/cat-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "🐱 Curiosity clicks. A pop-out ad makes people stop, look, and remember your business. Websites, content and AI tools under one umbrella. 🌂 #HotSpringsAR",
    likes: 1893,
    comments: 132,
    shares: 88,
  },
  {
    id: "coffeecup",
    title: "Coffee Cup Rise",
    niche: "Coffee shops & cafés",
    video: "/videos/scenes/coffeecup.mp4",
    poster: "/videos/scenes/coffeecup-poster.jpg",
    author: "MixedMakerShop",
    handle: "@mixedmakershop",
    location: "Hot Springs, Arkansas",
    caption:
      "☕ Almost reach out and grab it, right? Imagine this on YOUR café's page. We build coffee-shop sites that fill seats. Free mockup. #CoffeeShop #HotSpringsAR",
    likes: 1124,
    comments: 73,
    shares: 41,
  },
  {
    id: "print3d",
    title: "3D Print Rise",
    niche: "3D printing · makers",
    video: "/videos/scenes/print3d.mp4",
    poster: "/videos/scenes/print3d-poster.jpg",
    author: "GiGi's Print Shop",
    handle: "@gigisprintshop",
    location: "Hot Springs, Arkansas",
    caption:
      "🖨️ Watch it come to life. From a flat screen to a finished print — GiGi's Print Shop makes custom PLA parts and figures on demand. #3DPrinting #HotSpringsAR",
    likes: 967,
    comments: 52,
    shares: 33,
  },
  {
    id: "dog",
    title: "Dog Pop-Out",
    niche: "Lawn care & property care",
    video: "/videos/scenes/dog.mp4",
    poster: "/videos/scenes/dog-poster.jpg",
    author: "Fresh Cut Property Care",
    handle: "@freshcutpropertycare",
    location: "Hot Springs & Lonsdale, AR",
    caption:
      "🐕 Man's best friend approves. Fresh Cut Property Care keeps Hot Springs yards sharp — and a site that ranks keeps the calls coming. Free estimate. #LawnCare #HotSpringsAR",
    likes: 1045,
    comments: 67,
    shares: 48,
  },
];
